Hospital/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from register import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.first_page,name="home"),
    # path('user/',include('register.urls', namespace ='register_app')),
    path('dashboard/',views.dashboard,name="dashboard"),

    # path('customers/',include('customers.urls', namespace="customer_app")),
	# path('products/',include('products.urls', namespace="product_app")),
	# path('orders/',include('orders.urls', namespace="order_app")),
    path('donorreg/',include(('dreg.urls', 'dregsite'), namespace='dregsite')),
    path('search/',include(('search.urls','searchsite'), namespace='searchsite')),
    path('user/',include(('register.urls', 'register_app'), namespace='register_app')),
    path('customers/',include(('customers.urls', 'customer_app'), namespace='customer_app')),
    path('products/',include(('products.urls', 'product_app'), namespace='product_app')),
    path('orders/',include(('orders.urls', 'order_app'), namespace='order_app')),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name = 'passwordreset/password_reset_email.html'), 
		 name = "password_reset"),
	
	path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name = 'passwordreset/password_reset_sent.html'), 
		 name = "password_reset_done"),
	
	path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='passwordreset/password_reset_form.html'),
		 name="password_reset_confirm"),  

	path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='passwordreset/password_reset_complete.html'),
		 name="password_reset_complete"),
   
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dreg/urls.py
from django.urls import path
from .views import donorregdisplay
#, donorregsuccess

urlpatterns = [
    path('', donorregdisplay, name='dregsite'),
    path('donors', donorregdisplay, name='dregdisplay')
]    

orders/urls.py
from django.urls import path
from orders import views,pdfviews

#app_name = "order_app"

urlpatterns = [
    path('create/<int:cid>/', views.create, name = "create"),#I pass cid as for instance to show customer name when i click Add Order
    path('list/',views.index,name="list"),
    path('pdf/',pdfviews.GeneratePDF.as_view(),name="pdf"),
    path('edit/customer-id-<int:cid>/order-id-<int:oid>/',views.edit,name="edit"),
    path('search/',views.search,name="search"),
    path('delete/<int:oid>/',views.delete,name="delete"),
    
]

orders/models.py
from django.db import models

from customers.models import Customer
from products.models import Product

class Order(models.Model):
    status=(
        ('Pending','Pending'),
        ('Delivered','Delivered'),
        ('Out for delivery','out for delivery')   
    )
    
    customer=models.ForeignKey(Customer,null=True,on_delete=models.SET_NULL)
    product=models.ForeignKey(Product,null=True,on_delete=models.SET_NULL)

    
    created_at=models.DateTimeField(max_length=50,null=True,auto_now=True)
    status=models.CharField(max_length=100,null=True,choices=status)
    quantity = models.IntegerField(default=1,blank=False)

    class Meta:
        db_table = 'tbl_orders'
    
    
    def save(self,*args,**kwargs):
    	super().save(*args,**kwargs)
   
    
    
@property
def get_total_item_price(self):
    return self.quantity * self.product.price
    

orders/forms.py
from django import forms

from .models import Order,Product,Customer


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        
       
        exclude = ('total_price',)
       

orders/views.py
from django.shortcuts import render,redirect,get_object_or_404,reverse

from django.http import JsonResponse
from .models import Order,Customer,Product
from orders.forms import OrderForm
from orders.filters import OrderFilter
from django.forms import inlineformset_factory
from django.contrib import messages

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q

from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin


def create(request,cid):
    
    OrderFormSet = inlineformset_factory(Customer,Order,fields='__all__',exclude=('total_price',),extra=5) 
    cus = Customer.objects.get(pk=cid)
    formset = OrderFormSet(queryset=Order.objects.none(),instance=cus)
    if request.method=='POST':
        formset = OrderFormSet(request.POST,instance = cus)
        if formset.is_valid():
            formset.save()
        messages.success(request,"Order is successfully added",extra_tags = 'alert')
        return redirect('customer_app:view', cid)
    
    return render(request,'orders/create.html',{'formset':formset,'customer':cus})





@login_required(login_url='/user/login/')
def index(request):
    orders=Order.objects.all().order_by("-id")
    total_orders=orders.count()
    pending=orders.filter(status='Pending').count()
    delivered=orders.filter(status="Delivered").count()
    orders = pagination(request,orders)
         
    context={
        'orders':orders,'total_orders':total_orders,
        'orders_pending':pending,'orders_delivered':delivered,
        'start':orders.start_index(),
        'end':orders.end_index()
        
        }
    return render(request,'orders/index.html',context)


        
    


def pagination(request,object):
    page = request.GET.get('page', 1)
    paginator = Paginator(object, 5)
  
    try:
        orders = paginator.page(page)
    except PageNotAnInteger:
        orders = paginator.page(1)
    except EmptyPage:
     
        orders = paginator.page(paginator.num_pages)
        
    return orders

    
def search(request):
    data = dict()
    field_value = request.GET.get('query')
    print(field_value)
    
    if field_value:
        orders = Order.objects.filter(
                                            Q(product__name__contains=field_value)
                                           |Q(status__icontains=field_value) 
                                        
                                           | Q(quantity__contains=field_value)
                                            | Q(customer__name__contains=field_value)
                                           )
        context = {'orders': orders}
            
        data['html_list'] = render_to_string('orders/get_search_orders.html',context,request=request)
        return JsonResponse(data)
    

    else:
        orders = Order.objects.all()
       
        context = {'orders': orders}
        data['html_list'] = render_to_string('orders/get_search_orders.html',context,request=request)
        return JsonResponse(data)


def edit(request, cid, oid):    
    ord = get_object_or_404(Order,pk = oid)
    customer = get_object_or_404(Customer,pk=cid)
    form=OrderForm(instance=ord)
    
    
    if(request.method=='POST'):
        
        form=OrderForm(request.POST,instance=ord)
        if(form.is_valid()):
            form.save()
            messages.success(request,'Order is successfully updates.',extra_tags='alert')
            
            return redirect('customer_app:view', cid)
    return render(request,'orders/update.html',{'form':form,'customer_record':customer})


def delete(request, oid):
    ord = get_object_or_404(Order,pk = oid) 
    
    if request.method=='POST':
        ord.delete()  
        return redirect('order_app:list')
    
    return render(request,'orders/delete.html',{'orders':ord})

orders/templates/includes/card.html
{% extends 'base.html' %}
{% block title%}Card block{% endblock %}

{% block content %}
<br>
<div class="row mt-5 ml-6" style="margin-left:10%;">
	<div class="col">
		<div class="col-md">
			<div class="card bg-primary text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Total Orders</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{total_orders}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card bg-success text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Delivered</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{orders_delivered}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card bg-danger text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Pending</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{orders_pending}}</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>











{% endblock %}

orders/templates/includes/formsearch.html
   
    <form method="GET" action="{% url 'order_app:search' %}" id="js-search-form" class="form-inline" >
        {% csrf_token %}
         
        <input class="form-control mr-sm-2"  type="search" name="query" placeholder="Search..." aria-label="Search"
        aria-describedby="basic-addon2" />

    <button class="btn btn-primary my-2">Search</button>

</form>
       

orders/templates/includes/order_list.html
<div class="container">
    <div class="col-md-10">
        <table class="table table-sm table-responsive-sm table-hover text-nowrap table-striped table-bordered"
            style="margin-left:12%;">
            <thead class="thead-dark">
                <tr style="text-align: center;">
                    <th>Order Id</th>
                    <th>Cus.Id</th>
                    <!-- <th>Category</th> -->
                    <th>Product</th>
                    <!-- <th>Category</th> -->
                    <th>Quantity</th>
                    <th>Created</th>
                    <th>Status</th>

                    <th>Action</th>

                </tr>


            </thead>
            <tbody id="get_table_body">

                {% for order in orders %}

                <tr style="text-align: center;">
                    <td>{{order.id}}</td>
                    <td>{{order.customer.id}}</td>



                    <td>{{order.product.name}}</th>
                        <!-- <td>{{order.product.category}}</td> -->
                    <td>{{order.quantity}} {{order.product.unit}}</td>

                    <!--
     <td>{{order.product}}</th> also give same result for name
maila order table ma Product table ko access garda use product object
like above
product=models.ForeignKey(Product,null=True,on_delete=models.SET_NULL)
-->

                    <td>{{order.created_at}}</td>
                    <td>{{order.status}}</td>

                    <td><a href="{% url 'order_app:edit' order.customer.id order.id %}" class="btn btn-success btn-sm"><i
                                class="fa fa-edit"></i></a>


                            {% if user.is_superuser %}
                        <a href="{% url 'order_app:delete' order.id %}" class="btn btn-danger btn-sm"><i
                                class="fa fa-trash-alt"></i></a>



                            {% endif %}

                    </td>
                </tr>

                {% empty %}
                <tr>
                    <td colspan="7" class=" text-center alert alert-danger">No Order Found</td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script>
    $(document).ready(function(){
        $('#user-delete-button').on('click',function(){
            confirm("You should be admin to Delete Order Details")
            //setInterval('location.reload()', 1000);  
          
        })
    
    })
</script>